### ISSUE TITLE
장바구니 다이얼로그 에러

### ISSUE THREAD

**Issue by Yg323** [Dynamic-LAB/sinsungo_android#104]
## 개요
- 발생일시 : 2021. 04. 27
- 발생위치 : 장바구니 다이얼로그

## 증상
장바구니 다이얼로그를 사용하다가 dismiss 후 다시 틀면 각각 항목의 밑줄이 빨간색으로 표시

## 재현방법
다이얼로그를 틀고 아무 문구나 작성 후 삭제 -> 다시 다이얼로그 틀기 -> 빨간색 표시

## 스크린샷
<img width="395" alt="스크린샷 2021-04-27 오후 9 02 11" src="https://user-images.githubusercontent.com/45262992/116238028-d9285280-a79b-11eb-8f02-fb8b36fa51b7.png">
<img width="396" alt="스크린샷 2021-04-27 오후 9 02 40" src="https://user-images.githubusercontent.com/45262992/116238079-e9403200-a79b-11eb-8815-cdc359dcf844.png">

## 환경
- 기기 : 안드로이드 애뮬레이터

**Comment by leesh96** [comment]
#107 link
