### ISSUE TITLE
담당 프래그먼트 상단 레이아웃 변경 적용

### ISSUE THREAD

**Issue by leesh96** [Dynamic-LAB/sinsungo_android#112]
## 기능 개요
- 요약 : 담당 프래그먼트 상단 레이아웃 변경 적용
- link : #67 #111 

## 개발 내용
링크 이슈, PR 참고해서 담당 프래그먼트 상단 레이아웃 변경 적용

**Comment by jaeseuk** [comment]
저는 타이틀 따로 안해줬었슴다

**Comment by leesh96** [comment]
확인

> 저는 타이틀 따로 안해줬었슴다
