### ISSUE TITLE
버튼 스타일 생성

### ISSUE THREAD

**Issue by Yg323** [Dynamic-LAB/sinsungo_android#41]
## 기능 개요
- 요약 : 버튼 스타일 생성
- 개발자 : @Yg323

**Comment by leesh96** [comment]
해당 이슈 다이얼로그에 들어가는 버튼만 스타일 만들면 되는지??

**Comment by Yg323** [comment]
> 해당 이슈 다이얼로그에 들어가는 버튼만 스타일 만들면 되는지??

다이얼로그 이외에도 장바구니 기능의 추가하기 버튼도 생성해야됩니다.

**Comment by leesh96** [comment]
확인 버튼이랑 같은 스타일 쓰고 text 속성만 xml에서 따로 "추가"로 해주면 됩니다.

**Comment by Yg323** [comment]
> 확인 버튼이랑 같은 스타일 쓰고 text 속성만 xml에서 따로 "추가"로 해주면 됩니다.

네

**Comment by leesh96** [comment]
#62 해당 이슈에 포함
