### ISSUE TITLE
레시피 기능 개발

### ISSUE THREAD

**Issue by jaeseuk** [Dynamic-LAB/sinsungo_android#78]
## 기능 개요
- 요약 : 레시피 기능 개발
- 개발자 : @jaeseuk 
## 개발 내용
레시피 뷰모델 제작 #117 
레시피 리포지토리 패턴 제작 #119 
레세피 리사이클러뷰 구현 #120

**Comment by leesh96** [comment]
선생님 디테일 액티비티 제작까지 View 개발로 따로 빼주세요

**Comment by jaeseuk** [comment]
> 선생님 디테일 액티비티 제작까지 View 개발로 따로 빼주세요

오우오우 너무 늦게 봐버렸구만..
